<?php
header('Content-type: text/html; charset=utf-8');

$this->headTitle()->setSeparator(' - ')
     ->headTitle('七彩映像丶', 'PREPEND');

$this->headMeta()->appendName('Robots', 'index,follow,all')
                 ->appendName('Author', 'Zyk')

                 ->appendName('Accept-Encoding', 'gzip,deflate')
                 ->appendName('Content-Encoding', 'gzip');

$this->headMeta()->appendHttpEquiv('Expires', gmdate('D, d M Y H:i:s', 1552032618) . ' GMT')
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->charset)
                 ->appendHttpEquiv('Content-Script-Type', 'text/javascript')
                 ->appendHttpEquiv('Window-Target', '_top');

$this->headMeta()->appendHttpEquiv('Content-Language', 'zh-CN');
//$this->headLink()->prependStylesheet($this->pathCss . 'default.css');
$this->css()->append('adminIframe.css')->prepend('reset-fonts.css');


//$this->headScript()->appendFile($this->pathJs . 'general.js');
//$this->js()->append('general.js');

//$this->js()->append('backToTop.js');
//$this->inlineScript()->appendScript('window.setInterval("heartBeat(\'backToTopScroll\')", 1)');
echo $this->doctype($this->doctype).PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
echo $this->headTitle().PHP_EOL;
echo $this->headMeta().PHP_EOL;
echo $this->headLink().PHP_EOL;
echo $this->css().PHP_EOL;
//echo $this->headStyle();
//echo $this->headScript();
echo $this->js().PHP_EOL;
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body>
    <div id="iframeContainer">
        <?php echo $this->layout()->content;?>
    </div>
</body>
</html>