  <div class="logo fl">
    <div class="png"><a href="#"><img src="http://f/phpwind/images/admin/logo.png"></a></div>
    <div class="lun"> <a target="_blank" href="/">前台首页</a>&nbsp;&ndash;&nbsp;<a href="javascript:;">后台菜单</a></div>
  </div>
  <div id="guide">
    <ul class="fr">
      <li class="home">用户名：admin</li>
      <li>级别：manager</li>
      <li><a title="刷新主页面" onclick="parent.main.location.reload();" style="cursor: pointer;" class="s0">刷新</a></li>
      <li><a title="后退到前一页" onclick="parent.main.history.go(-1);" style="cursor: pointer;" class="s0">后退</a></li>
      <li><a href="/user/admin.php?adminjob=quit">注销</a></li>
    </ul>
  </div>