<?php
header('Content-type: text/html; charset=utf-8');

$this->headTitle()->setSeparator(' - ')
     ->headTitle('七彩映像丶\'s Blog', 'PREPEND');

$this->headMeta()->appendName('Robots', 'index,follow,all')
                 ->appendName('Keywords', 'Keywords')
                 ->appendName('Description', 'Description')
                 ->appendName('Author', 'Zyk')
                 ->appendName('Copyright', 'Copyright 2010-2012')

                 ->appendName('Generator', 'Zend Framework ' . Zend_Version::VERSION)
                 ->appendName('Accept-Encoding', 'gzip,deflate')
                 ->appendName('Content-Encoding', 'gzip');

$this->headMeta()->appendHttpEquiv('Expires', gmdate('D, d M Y H:i:s', 1552032618) . ' GMT')
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->charset)
                 ->appendHttpEquiv('Content-Script-Type', 'text/javascript')
                 ->appendHttpEquiv('Window-Target', '_top');

//$this->headMeta()->appendHttpEquiv('set-cookie', 'Mon,12 May 2020 00:20:00 GMT');

//$this->headMeta()->appendHttpEquiv('Content-Language', 'en-US');
$this->headMeta()->appendHttpEquiv('Content-Language', 'zh-CN');

//$this->headMeta()->appendHttpEquiv('Date', gmdate('D, d M Y H:i:s', time()) . ' GMT');
//$this->headMeta()->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s', time()) . ' GMT');

/*
// we plan to let the user to see the page when even offline.

$this->headMeta()->appendHttpEquiv('Pragma', 'no-cache');
$this->headMeta()->appendHttpEquiv('Cache-Control', 'no-cache');
*/
//$this->headMeta()->appendHttpEquiv('Refresh', '3600');

//$this->headMeta()->appendHttpEquiv('Site-Enter', 'revealTrans(Duration=3,Transition=1)');
//$this->headMeta()->appendHttpEquiv('Page-Exit', 'blendTrans(Duration=0.5)');

//$this->headLink()->prependStylesheet($this->pathCss . 'default.css');
$this->css()->append('admin.css')->prepend('reset-fonts.css');

$this->headLink(array('type' => 'image/x-icon',
                      'href' => $this->pathImg . 'favicon.ico',
                      'rel'  => 'SHORTCUT ICON',
                      'PREPEND'));

//$this->headScript()->appendFile($this->pathJs . 'general.js');
//$this->js()->append('general.js');

$this->js()->append('adminComon.js')->prepend('jquery-1.4.2.min.js');
//$this->inlineScript()->appendScript('window.setInterval("heartBeat(\'backToTopScroll\')", 1)');
echo $this->doctype($this->doctype).PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
echo $this->headTitle().PHP_EOL;
echo $this->headMeta().PHP_EOL;
echo $this->headLink().PHP_EOL;
echo $this->css().PHP_EOL;
//echo $this->headStyle();
//echo $this->headScript();
echo $this->js().PHP_EOL;
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

</head>
<body>
<div id="container">
	<div id="header"><?php echo $this->render('header.phtml'); //$this->layout()->menu; ?></div>
    <div id="content">
        <div id="leftPanel"><?php echo $this->render('menu.phtml');?></div>
        <div id="mainFrameContainer">
        	<iframe src="/admin/index/default" width="100%" height="100%" id="main" name="main" frameborder="0" scrolling="yes" style="overflow:visible;"></iframe>
        </div>
    </div>
</div>
</body>
</html>
