                <div id="post-4" class="post">
                    <h2 class="entry-title"><a href="#" title="PHP 的永久链接" rel="bookmark">PHP</a></h2>
    
                    <div class="entry-content">
                        <div class="entry-meta">
                            <div class=cat></div>
    
                            <span class="author vcard">由 <a class="url fn n" href="#" title="查看 admin 的所有日志">admin</a> 撰写</span>
                            <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="entry-date">2010/04/27 10:01</span>
                            <span class="cat-links">发表在 <a href="#" title="查看 Ajax 的全部文章" rel="category">Ajax</a></span>
    
                            <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="edit-link"><a class="post-edit-link" href="#" title="编辑文章">编辑</a></span>
                        <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="comments-link"><a href="#respond" title="PHP 上的评论">评论 (0)</a></span>
                        </div>
    
                        <div  class="entry-content-width">
                            <p>PHP</p>
                        </div>
                    </div>
                </div><!-- .post -->
    
    
    
                <div id="post-1" class="post">
    
                    <h2 class="entry-title"><a href="#" title="Hello world！ 的永久链接" rel="bookmark">Hello world！</a></h2>
    
                    <div class="entry-content">
                        <div class="entry-meta">
                            <div class=cat></div>
                            <span class="author vcard">由 <a class="url fn n" href="#" title="查看 admin 的所有日志">admin</a> 撰写</span>
    
                            <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="entry-date">2010/04/26 08:34</span>
                            <span class="cat-links">发表在 <a href="#" title="查看 Zend Framework 的全部文章" rel="category">Zend Framework</a></span>
                            <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="edit-link"><a class="post-edit-link" href="#" title="编辑文章">编辑</a></span>
    
                        <span class="meta-sep">&nbsp;|&nbsp;</span>
                            <span class="comments-link"><a href="#comments" title="Hello world！ 上的评论">评论 (2)</a></span>
                        </div>
    
                        <div class="entry-content-width">
                            <p>欢迎使用 WordPress 。这是系统自动生成的演示文章。编辑或者删除它，开始您的博客！</p>
                        </div>
    
                    </div>
                </div><!-- .post -->
    
                <div id="nav-below" class="navigation">
                    <div class="nav-previous"></div>
                    <div class="nav-next"></div>
                </div>