<div id="header">
    <h1 id="blog-title"><a href="#" title="七彩映像 Serven Color" rel="home">七彩映像</a></h1>
    <!-- Search -->
    <div id="search">
        <form action="#" method="get">
                <div id="search-input">
                <input id="search-input-input" type="text" size="13" value="" name="s" /><input type="submit" value="OK" name="" id="search-submit" />
                </div>
        </form>
    </div>	
</div><!--  #header -->
<div id="header_nav">
    <div id="menu">
        <ul>
            <li class="current_page_item"><a href="http://wordpress"> Home</a></li>	
            <li class="cat-item"><a href="#" title="查看 Ajax 下的所有文章">Ajax</a></li>
            <li class="cat-item"><a href="#" title="查看 Html Css 下的所有文章">Html Css</a></li>
            <li class="cat-item"><a href="#" title="查看 Javascript 下的所有文章">Javascript</a></li>
            <li class="cat-item"><a href="#" title="查看 MySQL 下的所有文章">MySQL</a></li>
            <li class="cat-item"><a href="#" title="查看 PHP 下的所有文章">PHP</a></li>
            <li class="cat-item"><a href="#" title="查看 Zend Framework 下的所有文章">Zend Framework</a></li>
            <li class="page_item"><a href="#" title="About">About</a></li>
            <li><div class="rss"><a href="#feed">RSS</a></div></li>
        </ul>
    </div><!-- #header_nav -->
</div>