        <div id="primary" class="sidebar">
            <ul class="xoxo">
    
                <li id="pages">
                    <h3>分页</h3>
                    <ul>
                        <li class="page_item"><a href="#" title="About">About</a></li>
                    </ul>
                </li>
    
                <li id="categories">
                    <h3>分类</h3>
                    <ul>
                        <li class="cat-item"><a href="#" title="查看 Ajax 下的所有文章">Ajax</a></li>
                        <li class="cat-item"><a href="#" title="查看 Html Css 下的所有文章">Html Css</a></li>
                        <li class="cat-item"><a href="#" title="查看 Javascript 下的所有文章">Javascript</a></li>
                        <li class="cat-item"><a href="#" title="查看 MySQL 下的所有文章">MySQL</a></li>
                        <li class="cat-item"><a href="#" title="查看 PHP 下的所有文章">PHP</a></li>
                        <li class="cat-item"><a href="#" title="查看 Zend Framework 下的所有文章">Zend Framework</a></li>
                    </ul>
                </li>
    
                <li id="archives">
                    <h3>存档</h3>
                    <ul>
                        <li><a href='#' title='2010年四月'>2010年四月</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- #primary .sidebar -->
        <div id="secondary" class="sidebar">
            <ul class="xoxo">
                <li id="search">
                    <h3><label for="s">搜索</label></h3>
                    <form id="searchform" class="blog-search" method="get" action="#">
                        <div>
                            <input id="s" name="s" type="text" class="text" value="" size="10" tabindex="1" />
                            <input type="submit" class="button" value="搜索" tabindex="2" />
                        </div>
                    </form>
                </li>
    
                <li id="linkcat-2" class="linkcat"><h3>链接表</h3>
                    <ul class='xoxo blogroll'>
                        <li><a href="#">Development Blog</a></li>
                        <li><a href="#">Documentation</a></li>
                        <li><a href="#">Plugins</a></li>
                        <li><a href="#">Suggest Ideas</a></li>
                        <li><a href="#">Support Forum</a></li>
                        <li><a href="#">Themes</a></li>
                        <li><a href="#">WordPress Planet</a></li>
                    </ul>
                </li>
                
                <li id="rss-links">
                    <h3>RSS源</h3>
                    <ul>
                        <li><a href="#" title="七彩映像 latest posts" rel="alternate" type="application/rss+xml">所有日志</a></li>
                        <li><a href="#" title="七彩映像 latest comments" rel="alternate" type="application/rss+xml">所有评论</a></li>
                    </ul>
                </li>
    
                <li id="meta">
                    <h3>Meta</h3>
                    <ul>
                        <li><a href="#">站点管理</a></li>
                        <li><a href="#">退出</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- #secondary .sidebar -->
